services:
    CoreShop\Bundle\PimcoreBundle\Controller\Admin\DynamicDropdownController:
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ]]
        tags:
            - { name: controller.service_arguments }
            - { name: container.service_subscriber }
