services:
    _defaults:
        public: true

    coreshop.pimcore_controller.grid: '@CoreShop\Bundle\PimcoreBundle\Controller\Admin\GridController'
    CoreShop\Bundle\PimcoreBundle\Controller\Admin\GridController:
        tags:
            - { name: controller.service_arguments }

    CoreShop\Bundle\PimcoreBundle\EventListener\Grid\ObjectListFilterListener:
        arguments:
            - '@coreshop.registry.grid.filter'
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.object.list.beforeListLoad, method: checkObjectList }

    coreshop.registry.grid.filter:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - 'CoreShop\Component\Pimcore\DataObject\Grid\GridFilter'
            - 'coreshop-grid-filter'

    coreshop.registry.grid.action:
        class: CoreShop\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - 'CoreShop\Component\Pimcore\DataObject\Grid\GridAction'
            - 'coreshop-grid-action'
