services:
    _defaults:
        public: true

    coreshop.registry.pimcore.document.editable:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\Pimcore\Document\DocumentTagFactoryInterface
            - document-tag-factories
        tags:
            - { name: coreshop.registry, type_hint: pimcoreDocumentTags }

    CoreShop\Bundle\PimcoreBundle\Loader\DependencyInjectionImplementationLoader:
        arguments:
            - '@coreshop.registry.pimcore.document.editable'
        tags:
            - { name: coreshop.pimcore.implementation_loader.document.editable }
