services:
    _defaults:
        public: true

    CoreShop\Component\Pimcore\Templating\Helper\LinkGeneratorHelperInterface: '@CoreShop\Component\Pimcore\Templating\Helper\LinkGeneratorHelper'
    CoreShop\Component\Pimcore\Templating\Helper\LinkGeneratorHelper:
        arguments:
            - '@coreshop.link_generator'
        tags:
          - { name: templating.helper, alias: coreshop_link }
