services:
    _defaults:
        public: true

    CoreShop\Component\Pimcore\Twig\Extension\AssetHelperExtensions:
        tags:
            - { name: twig.extension }

    CoreShop\Component\Pimcore\Twig\Extension\DocumentHelperExtensions:
        tags:
            - { name: twig.extension }

    CoreShop\Component\Pimcore\Twig\Extension\ObjectHelperExtensions:
        tags:
            - { name: twig.extension }

    CoreShop\Component\Pimcore\Twig\Extension\ObjectLinkGeneratorExtension:
        arguments:
            - '@CoreShop\Component\Pimcore\DataObject\LinkGenerator'
        tags:
            - { name: twig.extension }

    CoreShop\Component\Pimcore\Twig\Extension\LinkGeneratorExtensions:
        arguments:
            - '@CoreShop\Component\Pimcore\Templating\Helper\LinkGeneratorHelperInterface'
        tags:
            - { name: twig.extension }
